### ISSUE TITLE
Can't download via HACS

### ISSUE THREAD

**Issue by stomko11** [viktak/ha-cc-abalin-nameday#8]
When trying to download, I get "unknown error"

When checking system - log, following can be observed:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/base.py:1405
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:16:00 AM (4 occurrences)
Last logged: 8:44:54 AM

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_download_repository(ref=msg.get("version"))
  File "/config/custom_components/hacs/repositories/base.py", line 1417, in async_download_repository
    await self._ensure_download_capabilities(ref)
  File "/config/custom_components/hacs/repositories/base.py", line 1405, in _ensure_download_capabilities
    and self.hacs.core.ha_version < target_manifest.homeassistant
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/awesomeversion/awesomeversion.py", line 156, in __lt__
    raise AwesomeVersionCompareException(
awesomeversion.exceptions.AwesomeVersionCompareException: Can't compare <CalVer 2024.10.2> and <unknown core-2021.4.0>
```

**Comment by viktak** [comment]
> When trying to download

What are you trying to download?

**Comment by stomko11** [comment]
I am trying to install "Abalin Name Day" from HACS.
I find it in the repository - hit download - and download on the dialog that pops up:

![image](https://github.com/user-attachments/assets/2a18c5b5-ff30-40bc-9bf8-33bde14fe9a0)

After that I get:

![image](https://github.com/user-attachments/assets/a792c3c0-d593-465e-a270-f5b1d979b003)

**Comment by viktak** [comment]
I see.
I just tried it on a fresh install, and indeed, it wouldn't install automatically. Something must have changed in HA or HACS that prevents automatic installation, but I don't have the time to fiddle with it at the moment.
Manual installation still works, however, so I would suggest doing so until I figure it out.

**Comment by stomko11** [comment]
Perhaps change in hacs.json following:
```
"homeassistant": "core-2021.4.0",
```
To
```
"homeassistant": "2021.4.0",
```

**Comment by viktak** [comment]
@stomko11 Thank you, you just saved me a couple of hours of research.... :)

Indeed, that was the issue - it is now fixed, new version uploaded.

**Comment by stomko11** [comment]
Indeed it is working now!
